# Generated by Django 2.1 on 2018-08-26 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fornecedor.Telefone'),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='ddd',
            field=models.IntegerField(),
        ),
    ]
