# Generated by Django 2.1 on 2018-08-26 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedor', '0003_auto_20180826_1359'),
        ('rateio', '0002_rateiocontacontabil'),
        ('contacontabil', '0001_initial'),
        ('colaborador', '0001_initial'),
        ('retencoes', '0002_auto_20180826_1317'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rp', models.IntegerField()),
                ('forma_pagamento', models.CharField(max_length=50)),
                ('valor_nfe', models.FloatField()),
                ('detalhe_pagamento', models.TextField()),
                ('data_pagamento', models.DateField()),
                ('numero_nfe', models.IntegerField()),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colaborador.Colaborador')),
                ('conta_contabil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacontabil.ContaContabil')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Empresa')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedor.Fornecedor')),
                ('rateio', models.ManyToManyField(to='rateio.Rateio')),
                ('retencoes', models.ManyToManyField(to='retencoes.Retencoes')),
            ],
        ),
    ]
