# Generated by Django 2.1 on 2018-08-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rp',
            name='aprovada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rp',
            name='arquivo_boleto',
            field=models.FileField(blank=True, null=True, upload_to='arquivos_boleto'),
        ),
        migrations.AddField(
            model_name='rp',
            name='arquivo_nfe',
            field=models.FileField(blank=True, null=True, upload_to='arquivos_nfe'),
        ),
    ]
