# Generated by Django 2.1 on 2018-08-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('agencia', models.CharField(max_length=10)),
                ('conta', models.CharField(max_length=15)),
                ('operacao', models.CharField(max_length=5)),
                ('dv', models.CharField(max_length=1)),
            ],
        ),
    ]
