# Generated by Django 2.1 on 2018-08-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Retencoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('Acrescimo', 1), ('Desconto', 2)], max_length=5)),
                ('percentual', models.FloatField()),
                ('valor', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
