# Generated by Django 2.1 on 2018-08-26 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacontabil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('valor_orc', models.FloatField()),
                ('valor_realiz', models.FloatField(blank=True, null=True)),
                ('conta_contabil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacontabil.ContaContabil')),
            ],
        ),
    ]
