# Generated by Django 2.1 on 2018-08-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade', models.CharField(max_length=10)),
                ('razao_social', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=15)),
            ],
        ),
    ]
